language: scala
scala:
  - 2.11.11
  - 2.12.7
before_install:
 - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
